<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class QuestionSeeder extends Seeder
{
    public function run(): void
    {
        // Truncate dulu agar idempotent — aman dijalankan berkali-kali
        DB::table('questions')->truncate();

        DB::table('questions')->insert([
            // =========================================================
            // DOMAIN: governance (Tata Kelola Keamanan Informasi)
            // Total: 22 pertanyaan | L1=8, L2=8, L3=6
            // =========================================================
            ['domain' => 'governance', 'indicator' => '2.1', 'maturity_level' => 1, 'score_weight' => 3, 'order' => 1, 'question_text' => "Apakah pimpinan instansi/perusahaan anda secara prinsip dan resmi bertanggungjawab terhadap pelaksanaan program keamanan informasi (misal yang tercantum dalam ITSP), termasuk penetapan kebijakan terkait?", 'created_at' => now(), 'updated_at' => now()],
            ['domain' => 'governance', 'indicator' => '2.2', 'maturity_level' => 1, 'score_weight' => 3, 'order' => 2, 'question_text' => "Apakah instansi/perusahaan anda memiliki fungsi atau bagian yang secara spesifik mempunyai tugas dan tanggungjawab mengelola keamanan informasi dan menjaga kepatuhannya?", 'created_at' => now(), 'updated_at' => now()],
            ['domain' => 'governance', 'indicator' => '2.3', 'maturity_level' => 1, 'score_weight' => 3, 'order' => 3, 'question_text' => "Apakah pejabat/petugas pelaksana pengamanan informasi mempunyai wewenang yang sesuai untuk menerapkan dan menjamin kepatuhan program keamanan informasi?", 'created_at' => now(), 'updated_at' => now()],
            ['domain' => 'governance', 'indicator' => '2.4', 'maturity_level' => 1, 'score_weight' => 3, 'order' => 4, 'question_text' => "Apakah penanggungjawab pelaksanaan pengamanan informasi diberikan alokasi sumber daya yang sesuai untuk mengelola dan menjamin kepatuhan program keamanan informasi?", 'created_at' => now(), 'updated_at' => now()],
            ['domain' => 'governance', 'indicator' => '2.5', 'maturity_level' => 1, 'score_weight' => 3, 'order' => 5, 'question_text' => "Apakah peran pelaksana pengamanan informasi yang mencakup semua keperluan dipetakan dengan lengkap, termasuk kebutuhan audit internal dan persyaratan segregasi kewenangan?", 'created_at' => now(), 'updated_at' => now()],
            ['domain' => 'governance', 'indicator' => '2.6', 'maturity_level' => 1, 'score_weight' => 3, 'order' => 6, 'question_text' => "Apakah instansi/perusahaan anda sudah mendefinisikan persyaratan/standar kompetensi dan keahlian pelaksana pengelolaan keamanan informasi?", 'created_at' => now(), 'updated_at' => now()],
            ['domain' => 'governance', 'indicator' => '2.7', 'maturity_level' => 1, 'score_weight' => 3, 'order' => 7, 'question_text' => "Apakah semua pelaksana pengamanan informasi di instansi/perusahaan anda memiliki kompetensi dan keahlian yang memadai sesuai persyaratan/standar yang berlaku?", 'created_at' => now(), 'updated_at' => now()],
            ['domain' => 'governance', 'indicator' => '2.8', 'maturity_level' => 1, 'score_weight' => 3, 'order' => 8, 'question_text' => "Apakah instansi/perusahaan anda sudah menerapkan program sosialisasi dan peningkatan pemahaman untuk keamanan informasi, termasuk kepentingan kepatuhannya bagi semua pihak yang terkait?", 'created_at' => now(), 'updated_at' => now()],
            ['domain' => 'governance', 'indicator' => '2.9', 'maturity_level' => 2, 'score_weight' => 6, 'order' => 9, 'question_text' => "Apakah instansi/perusahaan anda menerapkan program peningkatan kompetensi dan keahlian untuk pejabat dan petugas pelaksana pengelolaan keamanan informasi?", 'created_at' => now(), 'updated_at' => now()],
            ['domain' => 'governance', 'indicator' => '2.10', 'maturity_level' => 2, 'score_weight' => 6, 'order' => 10, 'question_text' => "Apakah instansi/perusahaan anda sudah mengintegrasikan keperluan/persyaratan keamanan informasi dalam proses kerja yang ada?", 'created_at' => now(), 'updated_at' => now()],
            ['domain' => 'governance', 'indicator' => '2.11', 'maturity_level' => 2, 'score_weight' => 6, 'order' => 11, 'question_text' => "Apakah instansi/perusahaan anda sudah mengidentifikasikan data pribadi yang digunakan dalam proses kerja dan menerapkan pengamanan sesuai dengan peraturan perundangan yang berlaku?", 'created_at' => now(), 'updated_at' => now()],
            ['domain' => 'governance', 'indicator' => '2.12', 'maturity_level' => 2, 'score_weight' => 6, 'order' => 12, 'question_text' => "Apakah tanggungjawab pengelolaan keamanan informasi mencakup koordinasi dengan pihak pengelola/pengguna aset informasi internal dan eksternal maupun pihak lain yang berkepentingan, untuk mengidentifikasikan persyaratan/kebutuhan pengamanan (misal: pertukaran informasi atau kerjasama yang melibatkan informasi penting) dan menyelesaikan permasalahan yang ada?", 'created_at' => now(), 'updated_at' => now()],
            ['domain' => 'governance', 'indicator' => '2.13', 'maturity_level' => 2, 'score_weight' => 6, 'order' => 13, 'question_text' => "Apakah pengelola keamanan informasi secara proaktif berkoordinasi dengan satker terkait (SDM, Legal/Hukum, Umum, Keuangan dll) dan pihak eksternal yang berkepentingan (misal: regulator, aparat keamanan) untuk menerapkan dan menjamin kepatuhan pengamanan informasi terkait proses kerja yang melibatkan berbagai pihak?", 'created_at' => now(), 'updated_at' => now()],
            ['domain' => 'governance', 'indicator' => '2.14', 'maturity_level' => 2, 'score_weight' => 6, 'order' => 14, 'question_text' => "Apakah tanggungjawab untuk memutuskan, merancang, melaksanakan dan mengelola langkah kelangsungan layanan TIK (business continuity dan disaster recovery plans) sudah didefinisikan dan dialokasikan?", 'created_at' => now(), 'updated_at' => now()],
            ['domain' => 'governance', 'indicator' => '2.15', 'maturity_level' => 2, 'score_weight' => 6, 'order' => 15, 'question_text' => "Apakah penanggungjawab pengelolaan keamanan informasi melaporkan kondisi, kinerja/efektifitas dan kepatuhan program keamanan informasi kepada pimpinan instansi/perusahaan secara rutin dan resmi?", 'created_at' => now(), 'updated_at' => now()],
            ['domain' => 'governance', 'indicator' => '2.16', 'maturity_level' => 2, 'score_weight' => 6, 'order' => 16, 'question_text' => "Apakah kondisi dan permasalahan keamanan informasi di instansi/perusahaan anda menjadi konsiderans atau bagian dari proses pengambilan keputusan strategis di instansi/perusahaan anda?", 'created_at' => now(), 'updated_at' => now()],
            ['domain' => 'governance', 'indicator' => '2.17', 'maturity_level' => 3, 'score_weight' => 9, 'order' => 17, 'question_text' => "Apakah pimpinan satuan kerja di instansi/perusahaan anda menerapkan program khusus untuk mematuhi tujuan dan sasaran kepatuhan pengamanan informasi, khususnya yang mencakup aset informasi yang menjadi tanggungjawabnya?", 'created_at' => now(), 'updated_at' => now()],
            ['domain' => 'governance', 'indicator' => '2.18', 'maturity_level' => 3, 'score_weight' => 9, 'order' => 18, 'question_text' => "Apakah instansi/perusahaan anda sudah mendefinisikan metrik, paramater dan proses pengukuran kinerja pengelolaan keamanan informasi yang mencakup mekanisme, waktu pengukuran, pelaksananya, pemantauannya dan eskalasi pelaporannya?", 'created_at' => now(), 'updated_at' => now()],
            ['domain' => 'governance', 'indicator' => '2.19', 'maturity_level' => 3, 'score_weight' => 9, 'order' => 19, 'question_text' => "Apakah instansi/perusahaan anda sudah menerapkan program penilaian kinerja pengelolaan keamanan informasi bagi individu (pejabat & petugas) pelaksananya?", 'created_at' => now(), 'updated_at' => now()],
            ['domain' => 'governance', 'indicator' => '2.20', 'maturity_level' => 3, 'score_weight' => 9, 'order' => 20, 'question_text' => "Apakah instansi/perusahaan anda sudah menerapkan target dan sasaran pengelolaan keamanan informasi untuk berbagai area yang relevan, mengevaluasi pencapaiannya secara rutin, menerapkan langkah perbaikan untuk mencapai sasaran yang ada, termasuk pelaporan statusnya kepada pimpinan instansi/perusahaan?", 'created_at' => now(), 'updated_at' => now()],
            ['domain' => 'governance', 'indicator' => '2.21', 'maturity_level' => 3, 'score_weight' => 9, 'order' => 21, 'question_text' => "Apakah instansi/perusahaan anda sudah mengidentifikasi legislasi, perangkat hukum dan standar lainnya terkait keamanan informasi yang harus dipatuhi dan menganalisa tingkat kepatuhannya?", 'created_at' => now(), 'updated_at' => now()],
            ['domain' => 'governance', 'indicator' => '2.22', 'maturity_level' => 3, 'score_weight' => 9, 'order' => 22, 'question_text' => "Apakah instansi/perusahaan anda sudah mendefinisikan kebijakan dan langkah penanggulangan insiden keamanan informasi yang menyangkut pelanggaran hukum (pidana dan perdata)?", 'created_at' => now(), 'updated_at' => now()],

            // =========================================================
            // DOMAIN: risk_management (Pengelolaan Risiko Keamanan Informasi)
            // Total: 16 pertanyaan | L1=10, L2=4, L3=2
            // =========================================================
            ['domain' => 'risk_management', 'indicator' => '3.1', 'maturity_level' => 1, 'score_weight' => 3, 'order' => 23, 'question_text' => "Apakah instansi/perusahaan anda mempunyai program kerja pengelolaan risiko keamanan informasi yang terdokumentasi dan secara resmi digunakan?", 'created_at' => now(), 'updated_at' => now()],
            ['domain' => 'risk_management', 'indicator' => '3.2', 'maturity_level' => 1, 'score_weight' => 3, 'order' => 24, 'question_text' => "Apakah instansi/perusahaan anda sudah menetapkan penanggung jawab manajemen risiko dan eskalasi pelaporan status pengelolaan risiko keamanan informasi sampai ke tingkat pimpinan?", 'created_at' => now(), 'updated_at' => now()],
            ['domain' => 'risk_management', 'indicator' => '3.3', 'maturity_level' => 1, 'score_weight' => 3, 'order' => 25, 'question_text' => "Apakah instansi/perusahaan anda mempunyai kerangka kerja pengelolaan risiko keamanan informasi yang terdokumentasi dan secara resmi digunakan?", 'created_at' => now(), 'updated_at' => now()],
            ['domain' => 'risk_management', 'indicator' => '3.4', 'maturity_level' => 1, 'score_weight' => 3, 'order' => 26, 'question_text' => "Apakah kerangka kerja pengelolaan risiko ini mencakup definisi dan hubungan tingkat klasifikasi aset informasi, tingkat ancaman, kemungkinan terjadinya ancaman tersebut dan dampak kerugian terhadap instansi/perusahaan anda?", 'created_at' => now(), 'updated_at' => now()],
            ['domain' => 'risk_management', 'indicator' => '3.5', 'maturity_level' => 1, 'score_weight' => 3, 'order' => 27, 'question_text' => "Apakah instansi/perusahaan anda sudah menetapkan ambang batas tingkat risiko yang dapat diterima?", 'created_at' => now(), 'updated_at' => now()],
            ['domain' => 'risk_management', 'indicator' => '3.6', 'maturity_level' => 1, 'score_weight' => 3, 'order' => 28, 'question_text' => "Apakah instansi/perusahaan anda sudah mendefinisikan kepemilikan dan pihak pengelola (custodian) aset informasi yang ada, termasuk aset utama/penting dan proses kerja utama yang menggunakan aset tersebut?", 'created_at' => now(), 'updated_at' => now()],
            ['domain' => 'risk_management', 'indicator' => '3.7', 'maturity_level' => 1, 'score_weight' => 3, 'order' => 29, 'question_text' => "Apakah ancaman dan kelemahan yang terkait dengan aset informasi, terutama untuk setiap aset utama sudah teridentifikasi?", 'created_at' => now(), 'updated_at' => now()],
            ['domain' => 'risk_management', 'indicator' => '3.8', 'maturity_level' => 1, 'score_weight' => 3, 'order' => 30, 'question_text' => "Apakah dampak kerugian yang terkait dengan hilangnya/terganggunya fungsi aset utama sudah ditetapkan sesuai dengan definisi yang ada?", 'created_at' => now(), 'updated_at' => now()],
            ['domain' => 'risk_management', 'indicator' => '3.9', 'maturity_level' => 1, 'score_weight' => 3, 'order' => 31, 'question_text' => "Apakah instansi/perusahaan anda sudah menjalankan inisiatif analisa/kajian risiko keamanan informasi secara terstruktur terhadap aset informasi yang ada (untuk nantinya digunakan dalam mengidentifikasi langkah mitigasi atau penanggulangan yang menjadi bagian dari program pengelolaan keamanan informasi)?", 'created_at' => now(), 'updated_at' => now()],
            ['domain' => 'risk_management', 'indicator' => '3.10', 'maturity_level' => 1, 'score_weight' => 3, 'order' => 32, 'question_text' => "Apakah instansi/perusahaan anda sudah menyusun langkah mitigasi dan penanggulangan risiko yang ada?", 'created_at' => now(), 'updated_at' => now()],
            ['domain' => 'risk_management', 'indicator' => '3.11', 'maturity_level' => 2, 'score_weight' => 6, 'order' => 33, 'question_text' => "Apakah langkah mitigasi risiko disusun sesuai tingkat prioritas dengan target penyelesaiannya dan penanggungjawabnya, dengan memastikan efektifitas penggunaan sumber daya yang dapat menurunkan tingkat risiko ke ambang batas yang bisa diterima dengan meminimalisir dampak terhadap operasional layanan TIK?", 'created_at' => now(), 'updated_at' => now()],
            ['domain' => 'risk_management', 'indicator' => '3.12', 'maturity_level' => 2, 'score_weight' => 6, 'order' => 34, 'question_text' => "Apakah status penyelesaian langkah mitigasi risiko dipantau secara berkala, untuk memastikan penyelesaian atau kemajuan kerjanya?", 'created_at' => now(), 'updated_at' => now()],
            ['domain' => 'risk_management', 'indicator' => '3.13', 'maturity_level' => 2, 'score_weight' => 6, 'order' => 35, 'question_text' => "Apakah penyelesaian langkah mitigasi yang sudah diterapkan dievaluasi, melalui proses yang obyektif/terukur untuk memastikan konsistensi dan efektifitasnya?", 'created_at' => now(), 'updated_at' => now()],
            ['domain' => 'risk_management', 'indicator' => '3.14', 'maturity_level' => 2, 'score_weight' => 6, 'order' => 36, 'question_text' => "Apakah profil risiko berikut bentuk mitigasinya secara berkala dikaji ulang untuk memastikan akurasi dan validitasnya, termasuk merevisi profil terebut apabila ada perubahan kondisi yang signifikan atau keperluan penerapan bentuk pengamanan baru?", 'created_at' => now(), 'updated_at' => now()],
            ['domain' => 'risk_management', 'indicator' => '3.15', 'maturity_level' => 3, 'score_weight' => 9, 'order' => 37, 'question_text' => "Apakah kerangka kerja pengelolaan risiko secara berkala dikaji untuk memastikan/meningkatkan efektifitasnya?", 'created_at' => now(), 'updated_at' => now()],
            ['domain' => 'risk_management', 'indicator' => '3.16', 'maturity_level' => 3, 'score_weight' => 9, 'order' => 38, 'question_text' => "Apakah pengelolaan risiko menjadi bagian dari kriteria proses penilaian obyektif kinerja efektifitas pengamanan?", 'created_at' => now(), 'updated_at' => now()],

            // =========================================================
            // DOMAIN: framework (Kerangka Kerja Pengelolaan Keamanan Informasi)
            // Total: 32 pertanyaan | L1=12, L2=11, L3=9
            // =========================================================
            ['domain' => 'framework', 'indicator' => '4.1', 'maturity_level' => 1, 'score_weight' => 3, 'order' => 39, 'question_text' => "Apakah kebijakan dan prosedur maupun dokumen lainnya yang diperlukan terkait keamanan informasi sudah disusun dan dituliskan dengan jelas, dengan mencantumkan peran dan tanggung jawab pihak-pihak yang diberikan wewenang untuk menerapkannya?", 'created_at' => now(), 'updated_at' => now()],
            ['domain' => 'framework', 'indicator' => '4.2', 'maturity_level' => 1, 'score_weight' => 3, 'order' => 40, 'question_text' => "Apakah kebijakan keamanan informasi sudah ditetapkan secara formal, dipublikasikan kepada semua staf/karyawan termasuk pihak terkait dan dengan mudah diakses oleh pihak yang membutuhkannya?", 'created_at' => now(), 'updated_at' => now()],
            ['domain' => 'framework', 'indicator' => '4.3', 'maturity_level' => 1, 'score_weight' => 3, 'order' => 41, 'question_text' => "Apakah tersedia mekanisme untuk mengelola dokumen kebijakan dan prosedur keamanan informasi, termasuk penggunaan daftar induk, distribusi, penarikan dari peredaran dan penyimpanannya?", 'created_at' => now(), 'updated_at' => now()],
            ['domain' => 'framework', 'indicator' => '4.4', 'maturity_level' => 1, 'score_weight' => 3, 'order' => 42, 'question_text' => "Apakah tersedia proses (mencakup pelaksana, mekanisme, jadwal, materi, dan sasarannya) untuk mengkomunikasikan kebijakan keamanan informasi (dan perubahannya) kepada semua pihak terkait, termasuk pihak ketiga?", 'created_at' => now(), 'updated_at' => now()],
            ['domain' => 'framework', 'indicator' => '4.5', 'maturity_level' => 1, 'score_weight' => 3, 'order' => 43, 'question_text' => "Apakah keseluruhan kebijakan dan prosedur keamanan informasi yang ada merefleksikan kebutuhan mitigasi dari hasil kajian risiko keamanan informasi, maupun sasaran/obyetif tertentu yang ditetapkan oleh pimpinan instansi/perusahaan?", 'created_at' => now(), 'updated_at' => now()],
            ['domain' => 'framework', 'indicator' => '4.6', 'maturity_level' => 1, 'score_weight' => 3, 'order' => 44, 'question_text' => "Apakah tersedia proses untuk mengidentifikasi kondisi yang membahayakan keamanan infomasi dan menetapkannya sebagai insiden keamanan informasi untuk ditindak lanjuti sesuai prosedur yang diberlakukan?", 'created_at' => now(), 'updated_at' => now()],
            ['domain' => 'framework', 'indicator' => '4.7', 'maturity_level' => 1, 'score_weight' => 3, 'order' => 45, 'question_text' => "Apakah aspek keamanan informasi yang mencakup pelaporan insiden, menjaga kerahasiaan, HAKI, tata tertib penggunaan dan pengamanan aset maupun layanan TIK tercantum dalam kontrak dengan pihak ketiga?", 'created_at' => now(), 'updated_at' => now()],
            ['domain' => 'framework', 'indicator' => '4.8', 'maturity_level' => 2, 'score_weight' => 6, 'order' => 46, 'question_text' => "Apakah konsekwensi dari pelanggaran kebijakan keamanan informasi sudah didefinisikan, dikomunikasikan dan ditegakkan?", 'created_at' => now(), 'updated_at' => now()],
            ['domain' => 'framework', 'indicator' => '4.9', 'maturity_level' => 2, 'score_weight' => 6, 'order' => 47, 'question_text' => "Apakah tersedia prosedur resmi untuk mengelola suatu pengecualian terhadap penerapan keamanan informasi, termasuk proses untuk menindak lanjuti konsekwensi dari kondisi ini?", 'created_at' => now(), 'updated_at' => now()],
            ['domain' => 'framework', 'indicator' => '4.10', 'maturity_level' => 2, 'score_weight' => 6, 'order' => 48, 'question_text' => "Apakah instansi/perusahaan anda sudah menerapkan kebijakan dan prosedur operasional untuk mengelola implementasi security patch, alokasi tanggung jawab untuk memonitor adanya rilis security patch baru, memastikan pemasangannya dan melaporkannya?", 'created_at' => now(), 'updated_at' => now()],
            ['domain' => 'framework', 'indicator' => '4.11', 'maturity_level' => 2, 'score_weight' => 6, 'order' => 49, 'question_text' => "Apakah instansi/perusahaan anda sudah membahas aspek keamanan informasi dalam manajemen proyek yang terkait dengan ruang lingkup?", 'created_at' => now(), 'updated_at' => now()],
            ['domain' => 'framework', 'indicator' => '4.12', 'maturity_level' => 2, 'score_weight' => 6, 'order' => 50, 'question_text' => "Apakah instansi/perusahaan anda sudah menerapkan proses untuk mengevaluasi risiko terkait rencana pembelian (atau implementasi) sistem baru dan menanggulangi permasalahan yang muncul?", 'created_at' => now(), 'updated_at' => now()],
            ['domain' => 'framework', 'indicator' => '4.13', 'maturity_level' => 2, 'score_weight' => 6, 'order' => 51, 'question_text' => "Apakah instansi/perusahaan anda sudah menerapkan proses pengembangan sistem yang aman (Secure SDLC) dengan menggunakan prinsip atau metode sesuai standar platform teknologi yang digunakan?", 'created_at' => now(), 'updated_at' => now()],
            ['domain' => 'framework', 'indicator' => '4.14', 'maturity_level' => 2, 'score_weight' => 6, 'order' => 52, 'question_text' => "Apabila penerapan suatu sistem mengakibatkan timbulnya risiko baru atau terjadinya ketidakpatuhan terhadap kebijakan yang ada, apakah ada proses untuk menanggulangi hal ini, termasuk penerapan pengamanan baru (compensating control) dan jadwal penyelesaiannya?", 'created_at' => now(), 'updated_at' => now()],
            ['domain' => 'framework', 'indicator' => '4.15', 'maturity_level' => 2, 'score_weight' => 6, 'order' => 53, 'question_text' => "Apakah instansi/perusahaan anda memiliki fungsi atau bagian yang secara spesifik mempunyai tugas dan tanggungjawab terkait perkembangan ancaman keamanan informasi dan pengelolaannya (threat inteligence)?", 'created_at' => now(), 'updated_at' => now()],
            ['domain' => 'framework', 'indicator' => '4.16', 'maturity_level' => 2, 'score_weight' => 6, 'order' => 54, 'question_text' => "Apakah tersedia kerangka kerja pengelolaan perencanaan kelangsungan layanan TIK (business continuity planning) yang mendefinisikan persyaratan/konsiderans keamanan informasi, termasuk penjadwalan uji cobanya?", 'created_at' => now(), 'updated_at' => now()],
            ['domain' => 'framework', 'indicator' => '4.17', 'maturity_level' => 3, 'score_weight' => 9, 'order' => 55, 'question_text' => "Apakah kebijakan dan prosedur yang diperlukan terkait perkembangan ancaman keamanan informasi dan pengelolaannya (threat inteligence) sudah disusun dan dituliskan dengan jelas (proses pengumpulan data, analisa, dan identifikasi ancaman), dengan mencantumkan peran dan tanggung jawab pihak-pihak yang diberikan wewenang untuk menerapkannya?", 'created_at' => now(), 'updated_at' => now()],
            ['domain' => 'framework', 'indicator' => '4.18', 'maturity_level' => 3, 'score_weight' => 9, 'order' => 56, 'question_text' => "Apakah hasil analisis perkembangan ancaman keamanan informasi disampaikan kepada pihak yang bertanggung jawab untuk mitigasi risiko, dan memantau perkembangan mitigasi tersebut?", 'created_at' => now(), 'updated_at' => now()],
            ['domain' => 'framework', 'indicator' => '4.19', 'maturity_level' => 3, 'score_weight' => 9, 'order' => 57, 'question_text' => "Apakah perencanaan pemulihan bencana terhadap layanan TIK (disaster recovery plan) sudah mendefinisikan komposisi, peran, wewenang dan tanggungjawab tim yang ditunjuk?", 'created_at' => now(), 'updated_at' => now()],
            ['domain' => 'framework', 'indicator' => '4.20', 'maturity_level' => 3, 'score_weight' => 9, 'order' => 58, 'question_text' => "Apakah uji coba perencanaan pemulihan bencana terhadap layanan TIK (disaster recovery plan) sudah dilakukan minimal sekali dalam setahun atau apabila ada keperluan yang mendesak (seperti perubahan infrastruktur), dilaksanakan sesuai jadwal penerapan perubahannya?", 'created_at' => now(), 'updated_at' => now()],
            ['domain' => 'framework', 'indicator' => '4.21', 'maturity_level' => 3, 'score_weight' => 9, 'order' => 59, 'question_text' => "Apakah hasil dari perencanaan pemulihan bencana terhadap layanan TIK (disaster recovery plan) dievaluasi untuk menerapkan langkah perbaikan atau pembenahan yang diperlukan - misal, apabila hasil uji coba menunjukkan bahwa proses pemulihan tidak bisa (gagal) memenuhi persyaratan yang ada?", 'created_at' => now(), 'updated_at' => now()],
            ['domain' => 'framework', 'indicator' => '4.22', 'maturity_level' => 3, 'score_weight' => 9, 'order' => 60, 'question_text' => "Apakah seluruh kebijakan dan prosedur keamanan informasi dievaluasi kelayakannya secara berkala?", 'created_at' => now(), 'updated_at' => now()],
            ['domain' => 'framework', 'indicator' => '4.23', 'maturity_level' => 1, 'score_weight' => 3, 'order' => 61, 'question_text' => "Apakah instansi/perusahaan anda mempunyai strategi penerapan keamanan informasi sesuai hasil analisa risiko yang penerapannya dilakukan sebagai bagian dari rencana kerja organisasi?", 'created_at' => now(), 'updated_at' => now()],
            ['domain' => 'framework', 'indicator' => '4.24', 'maturity_level' => 1, 'score_weight' => 3, 'order' => 62, 'question_text' => "Apakah instansi/perusahaan anda mempunyai strategi penggunaan teknologi keamanan informasi yang penerapan dan pemutakhirannya disesuaikan dengan kebutuhan dan perubahan profil risiko?", 'created_at' => now(), 'updated_at' => now()],
            ['domain' => 'framework', 'indicator' => '4.25', 'maturity_level' => 1, 'score_weight' => 3, 'order' => 63, 'question_text' => "Apakah strategi penerapan keamanan informasi direalisasikan sebagai bagian dari pelaksanaan program kerja organisasi anda?", 'created_at' => now(), 'updated_at' => now()],
            ['domain' => 'framework', 'indicator' => '4.26', 'maturity_level' => 1, 'score_weight' => 3, 'order' => 64, 'question_text' => "Apakah instansi/perusahaan anda memiliki dan melaksanakan program audit internal yang dilakukan oleh pihak independen dengan cakupan keseluruhan aset informasi, kebijakan dan prosedur keamanan yang ada (atau sesuai dengan standar yang berlaku)?", 'created_at' => now(), 'updated_at' => now()],
            ['domain' => 'framework', 'indicator' => '4.27', 'maturity_level' => 1, 'score_weight' => 3, 'order' => 65, 'question_text' => "Apakah audit internal tersebut mengevaluasi tingkat kepatuhan, konsistensi dan efektivitas penerapan keamanan informasi?", 'created_at' => now(), 'updated_at' => now()],
            ['domain' => 'framework', 'indicator' => '4.28', 'maturity_level' => 2, 'score_weight' => 6, 'order' => 66, 'question_text' => "Apakah hasil audit internal tersebut dikaji/dievaluasi untuk mengidentifikasi langkah pembenahan dan pencegahan, ataupun inisiatif peningkatan kinerja keamanan informasi?", 'created_at' => now(), 'updated_at' => now()],
            ['domain' => 'framework', 'indicator' => '4.29', 'maturity_level' => 2, 'score_weight' => 6, 'order' => 67, 'question_text' => "Apakah hasil audit internal dilaporkan kepada pimpinan organisasi untuk menetapkan langkah perbaikan atau program peningkatan kinerja keamanan informasi?", 'created_at' => now(), 'updated_at' => now()],
            ['domain' => 'framework', 'indicator' => '4.30', 'maturity_level' => 3, 'score_weight' => 9, 'order' => 68, 'question_text' => "Apabila ada keperluan untuk merevisi kebijakan dan prosedur yang berlaku, apakah ada analisa untuk menilai aspek finansial (dampak biaya dan keperluan anggaran) ataupun perubahan terhadap infrastruktur dan pengelolaan perubahannya, sebagai prasyarat untuk menerapkannya?", 'created_at' => now(), 'updated_at' => now()],
            ['domain' => 'framework', 'indicator' => '4.31', 'maturity_level' => 3, 'score_weight' => 9, 'order' => 69, 'question_text' => "Apakah instansi/perusahaan anda secara periodik menguji dan mengevaluasi tingkat/status kepatuhan program keamanan informasi yang ada (mencakup pengecualian atau kondisi ketidakpatuhan lainnya) untuk memastikan bahwa keseluruhan inisiatif tersebut, termasuk langkah pembenahan yang diperlukan, telah diterapkan secara efektif?", 'created_at' => now(), 'updated_at' => now()],
            ['domain' => 'framework', 'indicator' => '4.32', 'maturity_level' => 3, 'score_weight' => 9, 'order' => 70, 'question_text' => "Apakah instansi/perusahaan anda mempunyai rencana dan program peningkatan keamanan informasi untuk jangka menengah/panjang (1-3-5 tahun) yang direalisasikan secara konsisten?", 'created_at' => now(), 'updated_at' => now()],

            // =========================================================
            // DOMAIN: asset_management (Pengelolaan Aset Informasi)
            // Total: 53 pertanyaan | L1=27, L2=19, L3=7
            // =========================================================
            ['domain' => 'asset_management', 'indicator' => '5.1', 'maturity_level' => 1, 'score_weight' => 3, 'order' => 71, 'question_text' => "Apakah tersedia daftar inventaris aset informasi dan aset yang berhubungan dengan proses teknologi informasi secara lengkap, akurat dan terpelihara? (termasuk kepemilikan aset)", 'created_at' => now(), 'updated_at' => now()],
            ['domain' => 'asset_management', 'indicator' => '5.2', 'maturity_level' => 1, 'score_weight' => 3, 'order' => 72, 'question_text' => "Apakah tersedia definisi klasifikasi aset informasi yang sesuai dengan peraturan perundangan yang berlaku?", 'created_at' => now(), 'updated_at' => now()],
            ['domain' => 'asset_management', 'indicator' => '5.3', 'maturity_level' => 1, 'score_weight' => 3, 'order' => 73, 'question_text' => "Apakah tersedia proses yang mengevaluasi dan mengklasifikasi aset informasi sesuai tingkat kepentingan aset bagi instansi/perusahaan dan keperluan pengamanannya?", 'created_at' => now(), 'updated_at' => now()],
            ['domain' => 'asset_management', 'indicator' => '5.4', 'maturity_level' => 1, 'score_weight' => 3, 'order' => 74, 'question_text' => "Apakah tersedia definisi tingkatan akses yang berbeda dari setiap klasifikasi aset informasi dan matriks yang merekam alokasi akses tersebut?", 'created_at' => now(), 'updated_at' => now()],
            ['domain' => 'asset_management', 'indicator' => '5.5', 'maturity_level' => 1, 'score_weight' => 3, 'order' => 75, 'question_text' => "Apakah tersedia proses untuk mengidentifikasi dan menginventarisir syarat retensi aset informasi sesuai dengan peraturan perundangan yang ada dan menghapusnya jika sudah melewati batas retensi tersebut?", 'created_at' => now(), 'updated_at' => now()],
            ['domain' => 'asset_management', 'indicator' => '5.6', 'maturity_level' => 1, 'score_weight' => 3, 'order' => 76, 'question_text' => "Apakah tersedia proses untuk mengevaluasi kepatuhan terhadap syarat retensi dan menghapus aset informasi jika sudah melewati batas retensi tersebut?", 'created_at' => now(), 'updated_at' => now()],
            ['domain' => 'asset_management', 'indicator' => '5.7', 'maturity_level' => 1, 'score_weight' => 3, 'order' => 77, 'question_text' => "Apakah tersedia proses pengelolaan perubahan terhadap sistem, proses bisnis dan proses teknologi informasi (termasuk perubahan konfigurasi) yang diterapkan secara konsisten?", 'created_at' => now(), 'updated_at' => now()],
            ['domain' => 'asset_management', 'indicator' => '5.8', 'maturity_level' => 1, 'score_weight' => 3, 'order' => 78, 'question_text' => "Apakah tersedia proses pengelolaan konfigurasi yang diterapkan secara konsisten?", 'created_at' => now(), 'updated_at' => now()],
            ['domain' => 'asset_management', 'indicator' => '5.9', 'maturity_level' => 1, 'score_weight' => 3, 'order' => 79, 'question_text' => "Apakah tersedia proses untuk merilis suatu aset baru ke dalam lingkungan operasional dan memutakhirkan inventaris aset informasi?", 'created_at' => now(), 'updated_at' => now()],
            ['domain' => 'asset_management', 'indicator' => '5.10', 'maturity_level' => 1, 'score_weight' => 3, 'order' => 80, 'question_text' => "Definisi tanggungjawab pengamanan informasi secara individual untuk semua personil di instansi/perusahaan anda", 'created_at' => now(), 'updated_at' => now()],
            ['domain' => 'asset_management', 'indicator' => '5.11', 'maturity_level' => 1, 'score_weight' => 3, 'order' => 81, 'question_text' => "Tata tertib penggunaan komputer, email, internet dan intranet", 'created_at' => now(), 'updated_at' => now()],
            ['domain' => 'asset_management', 'indicator' => '5.12', 'maturity_level' => 1, 'score_weight' => 3, 'order' => 82, 'question_text' => "Tata tertib pengamanan dan penggunaan aset instansi/perusahaan terkait HAKI", 'created_at' => now(), 'updated_at' => now()],
            ['domain' => 'asset_management', 'indicator' => '5.13', 'maturity_level' => 1, 'score_weight' => 3, 'order' => 83, 'question_text' => "Peraturan terkait instalasi piranti lunak di aset TI milik instansi/perusahaan", 'created_at' => now(), 'updated_at' => now()],
            ['domain' => 'asset_management', 'indicator' => '5.14', 'maturity_level' => 1, 'score_weight' => 3, 'order' => 84, 'question_text' => "Peraturan penggunaan data pribadi yang mensyaratkan pemberian ijin tertulis oleh pemilik data pribadi", 'created_at' => now(), 'updated_at' => now()],
            ['domain' => 'asset_management', 'indicator' => '5.15', 'maturity_level' => 1, 'score_weight' => 3, 'order' => 85, 'question_text' => "Pengelolaan identitas elektronik dan proses otentikasi (username & password) termasuk kebijakan terhadap pelanggarannya", 'created_at' => now(), 'updated_at' => now()],
            ['domain' => 'asset_management', 'indicator' => '5.16', 'maturity_level' => 1, 'score_weight' => 3, 'order' => 86, 'question_text' => "Persyaratan dan prosedur pengelolaan/pemberian akses, otentikasi dan otorisasi untuk menggunakan aset informasi", 'created_at' => now(), 'updated_at' => now()],
            ['domain' => 'asset_management', 'indicator' => '5.17', 'maturity_level' => 1, 'score_weight' => 3, 'order' => 87, 'question_text' => "Ketetapan terkait waktu penyimpanan untuk klasifikasi data yang ada dan syarat penghancuran data", 'created_at' => now(), 'updated_at' => now()],
            ['domain' => 'asset_management', 'indicator' => '5.18', 'maturity_level' => 1, 'score_weight' => 3, 'order' => 88, 'question_text' => "Ketetapan terkait pertukaran data dengan pihak eksternal dan pengamanannya", 'created_at' => now(), 'updated_at' => now()],
            ['domain' => 'asset_management', 'indicator' => '5.19', 'maturity_level' => 1, 'score_weight' => 3, 'order' => 89, 'question_text' => "Proses penyidikan/investigasi untuk menyelesaikan insiden terkait kegagalan keamanan informasi", 'created_at' => now(), 'updated_at' => now()],
            ['domain' => 'asset_management', 'indicator' => '5.20', 'maturity_level' => 1, 'score_weight' => 3, 'order' => 90, 'question_text' => "Prosedur back-up dan uji coba pengembalian data (restore) secara berkala", 'created_at' => now(), 'updated_at' => now()],
            ['domain' => 'asset_management', 'indicator' => '5.21', 'maturity_level' => 2, 'score_weight' => 6, 'order' => 91, 'question_text' => "Ketentuan pengamanan fisik yang disesuaikan dengan definisi zona dan klasifikasi aset yang ada di dalamnya", 'created_at' => now(), 'updated_at' => now()],
            ['domain' => 'asset_management', 'indicator' => '5.22', 'maturity_level' => 2, 'score_weight' => 6, 'order' => 92, 'question_text' => "Proses pengecekan latar belakang SDM", 'created_at' => now(), 'updated_at' => now()],
            ['domain' => 'asset_management', 'indicator' => '5.23', 'maturity_level' => 2, 'score_weight' => 6, 'order' => 93, 'question_text' => "Proses pelaporan insiden keamanan informasi kepada pihak eksternal ataupun pihak yang berwajib.", 'created_at' => now(), 'updated_at' => now()],
            ['domain' => 'asset_management', 'indicator' => '5.24', 'maturity_level' => 2, 'score_weight' => 6, 'order' => 94, 'question_text' => "Proses dan metoda untuk penghancuran informasi yang sudah tidak diperlukan dan sesuai dengan klasifikasi informasi (mis: secure delete, jenis/kerapatan shredder dll), termasuk didalamnya laporan bukti penghancuran informasi?", 'created_at' => now(), 'updated_at' => now()],
            ['domain' => 'asset_management', 'indicator' => '5.25', 'maturity_level' => 2, 'score_weight' => 6, 'order' => 95, 'question_text' => "Prosedur kajian penggunaan akses (user access review) dan hak aksesnya (user access rights) berikut langkah pembenahan apabila terjadi ketidaksesuaian (non-conformity) terhadap kebijakan yang berlaku", 'created_at' => now(), 'updated_at' => now()],
            ['domain' => 'asset_management', 'indicator' => '5.26', 'maturity_level' => 2, 'score_weight' => 6, 'order' => 96, 'question_text' => "Prosedur untuk user yang mutasi/keluar atau tenaga kontrak/outsource yang habis masa kerjanya.", 'created_at' => now(), 'updated_at' => now()],
            ['domain' => 'asset_management', 'indicator' => '5.27', 'maturity_level' => 3, 'score_weight' => 9, 'order' => 97, 'question_text' => "Apakah tersedia daftar data/informasi yang harus di-backup dan laporan analisa kepatuhan terhadap prosedur backup-nya?", 'created_at' => now(), 'updated_at' => now()],
            ['domain' => 'asset_management', 'indicator' => '5.28', 'maturity_level' => 3, 'score_weight' => 9, 'order' => 98, 'question_text' => "Apakah tersedia daftar rekaman pelaksanaan keamanan informasi dan bentuk pengamanan yang sesuai dengan klasifikasinya?", 'created_at' => now(), 'updated_at' => now()],
            ['domain' => 'asset_management', 'indicator' => '5.29', 'maturity_level' => 3, 'score_weight' => 9, 'order' => 99, 'question_text' => "Apakah telah diterapkan proses dan metoda untuk mengaburkan data (data masking) agar hanya dapat dilihat oleh pihak yang mempunyai otoritas sesuai regulasi atau kebijakan? Mis: pengamanan data pribadi, data sensitif", 'created_at' => now(), 'updated_at' => now()],
            ['domain' => 'asset_management', 'indicator' => '5.30', 'maturity_level' => 3, 'score_weight' => 9, 'order' => 100, 'question_text' => "Apakah tersedia prosedur penggunaan perangkat pengolah informasi milik pihak ketiga (termasuk perangkat milik pribadi dan mitra kerja/vendor) dengan memastikan aspek HAKI dan pengamanan akses yang digunakan?", 'created_at' => now(), 'updated_at' => now()],
            ['domain' => 'asset_management', 'indicator' => '5.31', 'maturity_level' => 2, 'score_weight' => 6, 'order' => 101, 'question_text' => "Apakah instansi/perusahaan sudah melakukan kajian risiko terkait penggunaan layanan berbasis cloud dan menyesuaikan kebijakan keamanan informasi terkait layanan ini?", 'created_at' => now(), 'updated_at' => now()],
            ['domain' => 'asset_management', 'indicator' => '5.32', 'maturity_level' => 2, 'score_weight' => 6, 'order' => 102, 'question_text' => "Apakah instansi/perusahaan sudah menetapkan data apa saja yang akan disimpan/diolah/dipertukarkan melalui layanan berbasis cloud?", 'created_at' => now(), 'updated_at' => now()],
            ['domain' => 'asset_management', 'indicator' => '5.33', 'maturity_level' => 2, 'score_weight' => 6, 'order' => 103, 'question_text' => "Apakah instansi/perusahaan sudah menetapkan kebijakan dan menerapkan langkah pengamanan data pribadi yang disimpan/diolah/dipertukarkan melalui layanan cloud?", 'created_at' => now(), 'updated_at' => now()],
            ['domain' => 'asset_management', 'indicator' => '5.34', 'maturity_level' => 2, 'score_weight' => 6, 'order' => 104, 'question_text' => "Apakah instansi/perusahaan sudah mengkaji, menetapkan pembagian tanggung jawab keamanan informasi antara perusahaan dan penyelenggara layanan cloud?", 'created_at' => now(), 'updated_at' => now()],
            ['domain' => 'asset_management', 'indicator' => '5.35', 'maturity_level' => 2, 'score_weight' => 6, 'order' => 105, 'question_text' => "Apakah instansi/perusahaan sudah mengkaji, menetapkan kriteria dan memastikan aspek hukum (jurisdiksi, hak dan kewenangan) terkait penggunaan layanan berbasis cloud?", 'created_at' => now(), 'updated_at' => now()],
            ['domain' => 'asset_management', 'indicator' => '5.36', 'maturity_level' => 2, 'score_weight' => 6, 'order' => 106, 'question_text' => "Apakah instansi/perusahaan sudah mengevaluasi penyelenggara layanan cloud terkait reputasi penyelenggaranya?", 'created_at' => now(), 'updated_at' => now()],
            ['domain' => 'asset_management', 'indicator' => '5.37', 'maturity_level' => 2, 'score_weight' => 6, 'order' => 107, 'question_text' => "Apakah instansi/perusahaan sudah menetapkan standar keamanan teknis penggunaan layanan cloud, termasuk aspek penggunaannya oleh pengguna di internal instansi/perusahaan?", 'created_at' => now(), 'updated_at' => now()],
            ['domain' => 'asset_management', 'indicator' => '5.38', 'maturity_level' => 2, 'score_weight' => 6, 'order' => 108, 'question_text' => "Apakah instansi/perusahaan sudah mengevaluasi kelaikan keamanan layanan cloud termasuk aspek ketersediaannya dan pemenuhan sertifikasi layanan berbasis ISO 27001?", 'created_at' => now(), 'updated_at' => now()],
            ['domain' => 'asset_management', 'indicator' => '5.39', 'maturity_level' => 2, 'score_weight' => 6, 'order' => 109, 'question_text' => "Apakah instansi/perusahaan sudah memiliki proses pelaporan insiden terkait layanan cloud?", 'created_at' => now(), 'updated_at' => now()],
            ['domain' => 'asset_management', 'indicator' => '5.40', 'maturity_level' => 3, 'score_weight' => 9, 'order' => 110, 'question_text' => "Apakah instansi/perusahaan sudah memiliki kebijakan, strategi dan proses untuk mengganti layanan cloud atau menyediakan fasilitas pengganti apabila terjadi gangguan sementara pada layanan tersebut?", 'created_at' => now(), 'updated_at' => now()],
            ['domain' => 'asset_management', 'indicator' => '5.41', 'maturity_level' => 3, 'score_weight' => 9, 'order' => 111, 'question_text' => "Apakah instansi/perusahaan sudah memiliki proses untuk menghentikan layanan cloud, termasuk proses pengamanan data yang ada (memindahkan dan menghapus data)?", 'created_at' => now(), 'updated_at' => now()],
            ['domain' => 'asset_management', 'indicator' => '5.42', 'maturity_level' => 1, 'score_weight' => 3, 'order' => 112, 'question_text' => "Apakah sudah diterapkan pengamanan fasilitas fisik (lokasi kerja) yang sesuai dengan kepentingan/klasifikasi aset informasi, secara berlapis dan dapat mencegah upaya akses oleh pihak yang tidak berwenang?", 'created_at' => now(), 'updated_at' => now()],
            ['domain' => 'asset_management', 'indicator' => '5.43', 'maturity_level' => 1, 'score_weight' => 3, 'order' => 113, 'question_text' => "Apakah tersedia proses untuk mengelola alokasi kunci masuk (fisik dan elektronik) ke fasilitas fisik?", 'created_at' => now(), 'updated_at' => now()],
            ['domain' => 'asset_management', 'indicator' => '5.44', 'maturity_level' => 1, 'score_weight' => 3, 'order' => 114, 'question_text' => "Apakah infrastruktur komputasi terlindungi dari dampak lingkungan atau api dan berada dalam kondisi dengan suhu dan kelembaban yang sesuai dengan prasyarat pabrikannya?", 'created_at' => now(), 'updated_at' => now()],
            ['domain' => 'asset_management', 'indicator' => '5.45', 'maturity_level' => 1, 'score_weight' => 3, 'order' => 115, 'question_text' => "Apakah infrastruktur komputasi yang terpasang terlindungi dari gangguan pasokan listrik atau dampak dari petir?", 'created_at' => now(), 'updated_at' => now()],
            ['domain' => 'asset_management', 'indicator' => '5.46', 'maturity_level' => 1, 'score_weight' => 3, 'order' => 116, 'question_text' => "Apakah infrastruktur komputasi yang terpasang dapat dipantau melalui CCTV?", 'created_at' => now(), 'updated_at' => now()],
            ['domain' => 'asset_management', 'indicator' => '5.47', 'maturity_level' => 1, 'score_weight' => 3, 'order' => 117, 'question_text' => "Apakah tersedia peraturan pengamanan perangkat komputasi milik instansi/perusahaan anda apabila digunakan di luar lokasi kerja resmi (kantor)?", 'created_at' => now(), 'updated_at' => now()],
            ['domain' => 'asset_management', 'indicator' => '5.48', 'maturity_level' => 1, 'score_weight' => 3, 'order' => 118, 'question_text' => "Apakah tersedia proses untuk memindahkan aset TIK (piranti lunak, perangkat keras, data/informasi dll) dari lokasi yang sudah ditetapkan (termasuk pemutakhiran lokasinya dalam daftar inventaris)?", 'created_at' => now(), 'updated_at' => now()],
            ['domain' => 'asset_management', 'indicator' => '5.49', 'maturity_level' => 2, 'score_weight' => 6, 'order' => 119, 'question_text' => "Apakah konstruksi ruang penyimpanan perangkat pengolah informasi penting menggunakan rancangan dan material yang dapat menanggulangi risiko kebakaran dan dilengkapi dengan fasilitas pendukung (deteksi kebakaran/asap, pemadam api, pengatur suhu dan kelembaban) yang sesuai?", 'created_at' => now(), 'updated_at' => now()],
            ['domain' => 'asset_management', 'indicator' => '5.50', 'maturity_level' => 2, 'score_weight' => 6, 'order' => 120, 'question_text' => "Apakah tersedia proses untuk memeriksa (inspeksi) dan merawat: perangkat komputer, fasilitas pendukungnya dan kelayakan keamanan lokasi kerja untuk menempatkan aset informasi penting?", 'created_at' => now(), 'updated_at' => now()],
            ['domain' => 'asset_management', 'indicator' => '5.51', 'maturity_level' => 2, 'score_weight' => 6, 'order' => 121, 'question_text' => "Apakah tersedia mekanisme pengamanan dalam pengiriman aset informasi (perangkat dan dokumen) yang melibatkan pihak ketiga?", 'created_at' => now(), 'updated_at' => now()],
            ['domain' => 'asset_management', 'indicator' => '5.52', 'maturity_level' => 2, 'score_weight' => 6, 'order' => 122, 'question_text' => "Apakah tersedia peraturan untuk mengamankan lokasi kerja penting (ruang server, ruang arsip) dari risiko perangkat atau bahan yang dapat membahayakan aset informasi (termasuk fasilitas pengolah informasi) yang ada di dalamnya? (misal larangan penggunaan telpon genggam di dalam ruang server, menggunakan kamera dll)", 'created_at' => now(), 'updated_at' => now()],
            ['domain' => 'asset_management', 'indicator' => '5.53', 'maturity_level' => 3, 'score_weight' => 9, 'order' => 123, 'question_text' => "Apakah tersedia proses untuk mengamankan lokasi kerja dari keberadaan/kehadiran pihak ketiga yang bekerja untuk kepentingan instansi/perusahaan anda?", 'created_at' => now(), 'updated_at' => now()],

            // =========================================================
            // DOMAIN: technology (Teknologi dan Keamanan Informasi)
            // Total: 35 pertanyaan | L1=14, L2=15, L3=6
            // =========================================================
            ['domain' => 'technology', 'indicator' => '6.1', 'maturity_level' => 1, 'score_weight' => 3, 'order' => 124, 'question_text' => "Apakah layanan TIK (sistem komputer) yang menggunakan internet sudah dilindungi dengan lebih dari 1 lapis pengamanan?", 'created_at' => now(), 'updated_at' => now()],
            ['domain' => 'technology', 'indicator' => '6.2', 'maturity_level' => 1, 'score_weight' => 3, 'order' => 125, 'question_text' => "Apakah jaringan komunikasi disegmentasi sesuai dengan kepentingannya (pembagian instansi/perusahaan, kebutuhan aplikasi, jalur akses khusus, dll)?", 'created_at' => now(), 'updated_at' => now()],
            ['domain' => 'technology', 'indicator' => '6.3', 'maturity_level' => 1, 'score_weight' => 3, 'order' => 126, 'question_text' => "Apakah tersedia konfigurasi standar untuk keamanan sistem bagi keseluruhan aset jaringan, sistem dan aplikasi, yang dimutakhirkan sesuai perkembangan (standar industri yang berlaku) dan kebutuhan?", 'created_at' => now(), 'updated_at' => now()],
            ['domain' => 'technology', 'indicator' => '6.4', 'maturity_level' => 2, 'score_weight' => 6, 'order' => 127, 'question_text' => "Apakah tersedia proses pengelolaan konfigurasi perangkat komputasi (server, perangkat jaringan, sistem operasi dan aplikasi) yang diterapkan secara konsisten?", 'created_at' => now(), 'updated_at' => now()],
            ['domain' => 'technology', 'indicator' => '6.5', 'maturity_level' => 3, 'score_weight' => 9, 'order' => 128, 'question_text' => "Apakah perangkat komputasi terpasang tersebut sudah dikaji ulang secara berkala sesuai dengan konfigurasi standard untuk keamanan sistem, dipantau efektivitasnya dan dimutakhirkan/disesuaikan konfigurasinya melalui proses Manajemen Perubahan (change management)?", 'created_at' => now(), 'updated_at' => now()],
            ['domain' => 'technology', 'indicator' => '6.6', 'maturity_level' => 1, 'score_weight' => 3, 'order' => 129, 'question_text' => "Apakah jaringan, sistem dan aplikasi yang digunakan secara rutin dipindai untuk mengidentifikasi kemungkinan adanya celah kelemahan atau perubahan/keutuhan konfigurasi?", 'created_at' => now(), 'updated_at' => now()],
            ['domain' => 'technology', 'indicator' => '6.7', 'maturity_level' => 1, 'score_weight' => 3, 'order' => 130, 'question_text' => "Apakah keseluruhan infrastruktur jaringan, sistem dan aplikasi dirancang untuk memastikan ketersediaan (rancangan redundan) sesuai kebutuhan/persyaratan yang ada?", 'created_at' => now(), 'updated_at' => now()],
            ['domain' => 'technology', 'indicator' => '6.8', 'maturity_level' => 1, 'score_weight' => 3, 'order' => 131, 'question_text' => "Apakah keseluruhan infrastruktur jaringan, sistem dan aplikasi dimonitor untuk memastikan ketersediaan kapasitas yang cukup untuk kebutuhan yang ada dan efektivitas keamanannya?", 'created_at' => now(), 'updated_at' => now()],
            ['domain' => 'technology', 'indicator' => '6.9', 'maturity_level' => 1, 'score_weight' => 3, 'order' => 132, 'question_text' => "Apakah setiap perubahan dalam sistem informasi secara otomatis terekam di dalam log?", 'created_at' => now(), 'updated_at' => now()],
            ['domain' => 'technology', 'indicator' => '6.10', 'maturity_level' => 1, 'score_weight' => 3, 'order' => 133, 'question_text' => "Apakah upaya akses oleh yang tidak berhak secara otomatis terekam di dalam log?", 'created_at' => now(), 'updated_at' => now()],
            ['domain' => 'technology', 'indicator' => '6.11', 'maturity_level' => 1, 'score_weight' => 3, 'order' => 134, 'question_text' => "Apakah semua log dianalisa secara berkala untuk memastikan akurasi, validitas dan kelengkapan isinya (untuk kepentingan jejak audit dan forensik)?", 'created_at' => now(), 'updated_at' => now()],
            ['domain' => 'technology', 'indicator' => '6.12', 'maturity_level' => 1, 'score_weight' => 3, 'order' => 135, 'question_text' => "Apakah instansi/perusahaan anda menerapkan enkripsi untuk melindungi aset informasi penting sesuai kebijakan pengelolaan yang ada?", 'created_at' => now(), 'updated_at' => now()],
            ['domain' => 'technology', 'indicator' => '6.13', 'maturity_level' => 2, 'score_weight' => 6, 'order' => 136, 'question_text' => "Apakah instansi/perusahaan anda mempunyai standar dalam menggunakan enkripsi?", 'created_at' => now(), 'updated_at' => now()],
            ['domain' => 'technology', 'indicator' => '6.14', 'maturity_level' => 2, 'score_weight' => 6, 'order' => 137, 'question_text' => "Apakah instansi/perusahaan anda menerapkan pengamanan untuk mengelola kunci enkripsi (termasuk sertifikat elektronik) yang digunakan, termasuk siklus penggunaannya?", 'created_at' => now(), 'updated_at' => now()],
            ['domain' => 'technology', 'indicator' => '6.15', 'maturity_level' => 2, 'score_weight' => 6, 'order' => 138, 'question_text' => "Apakah semua sistem dan aplikasi secara otomatis mendukung dan menerapkan penggantian password secara otomatis, termasuk menon-aktifkan password, mengatur kompleksitas/panjangnya dan penggunaan kembali password lama?", 'created_at' => now(), 'updated_at' => now()],
            ['domain' => 'technology', 'indicator' => '6.16', 'maturity_level' => 2, 'score_weight' => 6, 'order' => 139, 'question_text' => "Apakah akses yang digunakan untuk mengelola sistem (administrasi sistem) menggunakan bentuk pengamanan khusus yang berlapis?", 'created_at' => now(), 'updated_at' => now()],
            ['domain' => 'technology', 'indicator' => '6.17', 'maturity_level' => 2, 'score_weight' => 6, 'order' => 140, 'question_text' => "Apakah sistem dan aplikasi yang digunakan sudah menerapkan pembatasan waktu akses termasuk otomatisasi proses timeouts, lockout setelah kegagalan login, dan penarikan akses?", 'created_at' => now(), 'updated_at' => now()],
            ['domain' => 'technology', 'indicator' => '6.18', 'maturity_level' => 2, 'score_weight' => 6, 'order' => 141, 'question_text' => "Apakah instansi/perusahaan anda menerapkan pengamanan untuk mendeteksi dan mencegah penggunaan akses jaringan (termasuk jaringan nirkabel) yang tidak resmi?", 'created_at' => now(), 'updated_at' => now()],
            ['domain' => 'technology', 'indicator' => '6.19', 'maturity_level' => 1, 'score_weight' => 3, 'order' => 142, 'question_text' => "Apakah instansi/perusahaan anda menerapkan bentuk pengamanan khusus untuk melindungi akses dari luar instansi/perusahaan?", 'created_at' => now(), 'updated_at' => now()],
            ['domain' => 'technology', 'indicator' => '6.20', 'maturity_level' => 1, 'score_weight' => 3, 'order' => 143, 'question_text' => "Apakah sistem operasi untuk setiap perangkat desktop dan server dimutakhirkan dengan versi terkini?", 'created_at' => now(), 'updated_at' => now()],
            ['domain' => 'technology', 'indicator' => '6.21', 'maturity_level' => 1, 'score_weight' => 3, 'order' => 144, 'question_text' => "Apakah setiap desktop dan server dilindungi dari penyerangan virus (malware)?", 'created_at' => now(), 'updated_at' => now()],
            ['domain' => 'technology', 'indicator' => '6.22', 'maturity_level' => 2, 'score_weight' => 6, 'order' => 145, 'question_text' => "Apakah ada rekaman dan hasil analisa (jejak audit - audit trail) yang mengkonfirmasi bahwa antivirus/antimalware telah dimutakhirkan secara rutin dan sistematis?", 'created_at' => now(), 'updated_at' => now()],
            ['domain' => 'technology', 'indicator' => '6.23', 'maturity_level' => 2, 'score_weight' => 6, 'order' => 146, 'question_text' => "Apakah adanya laporan penyerangan virus/malware yang gagal/sukses ditindaklanjuti dan diselesaikan?", 'created_at' => now(), 'updated_at' => now()],
            ['domain' => 'technology', 'indicator' => '6.24', 'maturity_level' => 2, 'score_weight' => 6, 'order' => 147, 'question_text' => "Apakah instansi/perusahaan anda secara rutin menganalisa dan menetapkan website yang membahayakan perusahaan atau tidak seharusnya diakses karyawan? Untuk selanjutnya website tersebut diblok agar tidak dapat diakses.", 'created_at' => now(), 'updated_at' => now()],
            ['domain' => 'technology', 'indicator' => '6.25', 'maturity_level' => 2, 'score_weight' => 6, 'order' => 148, 'question_text' => "Apakah keseluruhan jaringan, sistem dan aplikasi sudah menggunakan mekanisme sinkronisasi waktu yang akurat, sesuai dengan standar yang ada?", 'created_at' => now(), 'updated_at' => now()],
            ['domain' => 'technology', 'indicator' => '6.26', 'maturity_level' => 2, 'score_weight' => 6, 'order' => 149, 'question_text' => "Apakah instansi/perusahaan anda sudah menetapkan prinsip pengembangan aplikasi yang aman (secure coding) yang digunakan untuk pengembangan aplikasi secara internal (in-house) maupun yang melibatkan pihak eksternal? misal: menggunakan standard OWASP 10", 'created_at' => now(), 'updated_at' => now()],
            ['domain' => 'technology', 'indicator' => '6.27', 'maturity_level' => 2, 'score_weight' => 6, 'order' => 150, 'question_text' => "Apakah instansi/perusahaan anda sudah menerapkan proses perencanaan pengembangan sistem? (Dengan mempertimbangkan hasil pemrograman yang tidak baik/laik pada sistem sebelumnya, konfigurasi software development tool yang aman (secure), kontrol terhadap lingkungan pengembangan, desain arsitektur yang aman)", 'created_at' => now(), 'updated_at' => now()],
            ['domain' => 'technology', 'indicator' => '6.28', 'maturity_level' => 2, 'score_weight' => 6, 'order' => 151, 'question_text' => "Apakah instansi/perusahaan anda menerapkan proses source code review (baik secara manual atau menggunakan piranti lunak) sebelum dijalankan di lingkungan produksi?", 'created_at' => now(), 'updated_at' => now()],
            ['domain' => 'technology', 'indicator' => '6.29', 'maturity_level' => 1, 'score_weight' => 3, 'order' => 152, 'question_text' => "Apakah instansi/perusahaan anda menerapkan kontrol akses untuk source code aplikasi?", 'created_at' => now(), 'updated_at' => now()],
            ['domain' => 'technology', 'indicator' => '6.30', 'maturity_level' => 2, 'score_weight' => 6, 'order' => 153, 'question_text' => "Apakah setiap aplikasi yang ada memiliki spesifikasi dan fungsi keamanan yang diverifikasi/validasi pada saat proses pengembangan dan uji coba?", 'created_at' => now(), 'updated_at' => now()],
            ['domain' => 'technology', 'indicator' => '6.31', 'maturity_level' => 3, 'score_weight' => 9, 'order' => 154, 'question_text' => "Apakah instansi/perusahaan anda secara rutin menganalisa dan memperbaiki jika ditemukenali ancaman baru (misal adanya laporan kelemahan dan/atau teknik eksploit baru) yang berdampak pada keamanan sistem aplikasi?", 'created_at' => now(), 'updated_at' => now()],
            ['domain' => 'technology', 'indicator' => '6.32', 'maturity_level' => 3, 'score_weight' => 9, 'order' => 155, 'question_text' => "Apakah instansi/perusahaan anda menerapkan lingkungan pengembangan dan uji coba yang sudah diamankan sesuai dengan standar platform teknologi yang ada dan digunakan untuk seluruh siklus hidup sistem yang dibangun?", 'created_at' => now(), 'updated_at' => now()],
            ['domain' => 'technology', 'indicator' => '6.33', 'maturity_level' => 3, 'score_weight' => 9, 'order' => 156, 'question_text' => "Apakah instansi/perusahaan sudah menerapkan proses atau mekanisme untuk mencegah terungkapnya informasi sensitif ke luar dari perusahaan (misal membatasi/mengkarantina lampiran email atau memblokir pengiriman dokumen/data ke luar)?", 'created_at' => now(), 'updated_at' => now()],
            ['domain' => 'technology', 'indicator' => '6.34', 'maturity_level' => 3, 'score_weight' => 9, 'order' => 157, 'question_text' => "Apakah instansi/perusahaan sudah menerapkan teknologi (DLP Data Leakage Prevention) untuk mencegah terungkapnya informasi sensitif ke luar dari perusahaan?", 'created_at' => now(), 'updated_at' => now()],
            ['domain' => 'technology', 'indicator' => '6.35', 'maturity_level' => 3, 'score_weight' => 9, 'order' => 158, 'question_text' => "Apakah instansi/perusahaan anda melibatkan pihak independen untuk mengkaji kehandalan keamanan informasi secara rutin?", 'created_at' => now(), 'updated_at' => now()],
        ]);
    }
}
