/* This file is generated by Ziggy. */
declare module 'ziggy-js' {
  interface RouteList {
    "boost.browser-logs": [],
    "login": [],
    "login.store": [],
    "logout": [],
    "password.confirm": [],
    "password.confirmation": [],
    "password.confirm.store": [],
    "dashboard": [],
    "leader.index": [],
    "leader.create": [],
    "leader.store": [],
    "leader.edit": [
        {
            "name": "leader",
            "required": true,
            "binding": "id"
        }
    ],
    "leader.update": [
        {
            "name": "leader",
            "required": true,
            "binding": "id"
        }
    ],
    "leader.destroy": [
        {
            "name": "leader",
            "required": true,
            "binding": "id"
        }
    ],
    "question.index": [],
    "question.create": [],
    "question.store": [],
    "question.edit": [
        {
            "name": "question",
            "required": true,
            "binding": "id"
        }
    ],
    "question.update": [
        {
            "name": "question",
            "required": true,
            "binding": "id"
        }
    ],
    "question.destroy": [
        {
            "name": "question",
            "required": true,
            "binding": "id"
        }
    ],
    "ahp.pairwise": [],
    "ahp.store-pairwise": [],
    "ahp.result": [],
    "kami.calculate": [],
    "kami.process": [],
    "kami.result": [],
    "kami.show": [
        {
            "name": "kamiIndex",
            "required": true,
            "binding": "id"
        }
    ],
    "report.index": [],
    "report.export-pdf": [
        {
            "name": "kamiIndex",
            "required": true,
            "binding": "id"
        }
    ],
    "report.export-excel": [],
    "questionnaire.index": [],
    "questionnaire.fill": [],
    "questionnaire.submit": [],
    "questionnaire.result": [],
    "storage.local": [
        {
            "name": "path",
            "required": true
        }
    ]
}
}
export {};
